[package]
name = "giffgaff_new"
version = "0.1.0"
edition = "2024"

[dependencies]
base62 = "2.2.1"
fantoccini = "0.21.5"
rand = "0.9.1"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.45.0", features = ["rt-multi-thread", "macros"] }
toml = "0.8.22"
